name = "nct-frontend"
compatibility_date = "2026-04-20"
workers_dev = true
routes = [
  { pattern = "www.victimsunion.org", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
VITE_NCT_API_SQL_PUBLIC_DATA_URL="https://form.victimsunion.org"
VITE_NCT_SUB_FORM_URL="https://testbk.medicago.top/form"