name = "nct-frontend"
compatibility_date = "2026-04-20"
workers_dev = true
routes = [
  { pattern = "form.victimsunion.org", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "NCT_DB"
database_id = "f8b9618f-7f20-4ae4-88e3-64080a5a0bcb"